name       : python-pypdf2
version    : 2.1.0
release    : 10
source     :
    - https://files.pythonhosted.org/packages/c9/79/b18048e7a1a286806e80eca1b44f921494856c4236914ebc691533ea5eb4/PyPDF2-2.1.0.tar.gz : 768a7128b60697187de776345e6f922913517f5f7deecca550dce8f901667599
license    : BSD-3-Clause
component  : programming.python
summary    : Utility to read and write PDFs with Python
description: |
    PyPDF2 is a pure-python PDF library capable of splitting, merging together, cropping, and transforming the pages of PDF files. It can also add custom data, viewing options, and passwords to PDF files. It can retrieve text and metadata from PDFs as well as merge entire files together.
build      : |
    %python3_setup
install    : |
    %python3_install
