name       : python-pypdf2
version    : 2.10.5
release    : 17
source     :
    - https://files.pythonhosted.org/packages/fb/95/36949c9a969dba2af516f6f02250e54a544f74bf89dfb5ed481ea408b630/PyPDF2-2.10.5.tar.gz : a568453329f8ad73bb001bcf70fd2fd97ec6525669c54552b2b9e99c2e469459
license    : BSD-3-Clause
component  : programming.python
summary    : Utility to read and write PDFs with Python
description: |
    PyPDF2 is a pure-python PDF library capable of splitting, merging together, cropping, and transforming the pages of PDF files. It can also add custom data, viewing options, and passwords to PDF files. It can retrieve text and metadata from PDFs as well as merge entire files together.
build      : |
    %python3_setup
install    : |
    %python3_install
