name       : python-pypdf2
version    : 2.0.0
release    : 9
source     :
    - https://files.pythonhosted.org/packages/40/27/7ac08d83b15c391c3f1e9644bfacaf4e45aef670902af2235eb92b0bf2df/PyPDF2-2.0.0.tar.gz : 6c2c686cbdad1fa6d42a8cafb5d2f033d1798dd00e13e8d7691b510c567efa34
license    : BSD-3-Clause
component  : programming.python
summary    : Utility to read and write PDFs with Python
description: |
    PyPDF2 is a pure-python PDF library capable of splitting, merging together, cropping, and transforming the pages of PDF files. It can also add custom data, viewing options, and passwords to PDF files. It can retrieve text and metadata from PDFs as well as merge entire files together.
build      : |
    %python3_setup
install    : |
    %python3_install
