name       : python-pypdf2
version    : 2.10.4
release    : 16
source     :
    - https://files.pythonhosted.org/packages/58/45/ab8d7d04447c503d9aa393ea917a4e105dd716b5ffe431983b23f6665711/PyPDF2-2.10.4.tar.gz : f090c5fc7990cf5a6d6364ce2362834974e32136d52291babb2372e5d647d188
license    : BSD-3-Clause
component  : programming.python
summary    : Utility to read and write PDFs with Python
description: |
    PyPDF2 is a pure-python PDF library capable of splitting, merging together, cropping, and transforming the pages of PDF files. It can also add custom data, viewing options, and passwords to PDF files. It can retrieve text and metadata from PDFs as well as merge entire files together.
build      : |
    %python3_setup
install    : |
    %python3_install
